# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/system_constr.xdc

# XDC: /home/krisemi_satcom/adi/hdl/projects/common/zc702/zc702_system_constr.xdc

# Block Designs: bd/design_with_dvb_s2/design_with_dvb_s2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2 || ORIG_REF_NAME==design_with_dvb_s2} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_GND_1_0/design_with_dvb_s2_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_GND_1_0 || ORIG_REF_NAME==design_with_dvb_s2_GND_1_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_ad9361_0/design_with_dvb_s2_axi_ad9361_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_ad9361_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_ad9361_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_ad9361_adc_dma_0/design_with_dvb_s2_axi_ad9361_adc_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_ad9361_dac_fifo_0/design_with_dvb_s2_axi_ad9361_dac_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_ad9361_dac_fifo_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_ad9361_dac_fifo_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_xbar_0/design_with_dvb_s2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_xbar_0 || ORIG_REF_NAME==design_with_dvb_s2_xbar_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_cpu_interconnect_0/design_with_dvb_s2_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_cpu_interconnect_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_cpu_interconnect_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_hp0_interconnect_0/design_with_dvb_s2_axi_hp0_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_hp0_interconnect_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_hp0_interconnect_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_hp1_interconnect_0/design_with_dvb_s2_axi_hp1_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_hp1_interconnect_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_hp1_interconnect_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_sysid_0_0/design_with_dvb_s2_axi_sysid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_sysid_0_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_sysid_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_rom_sys_0_0/design_with_dvb_s2_rom_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_rom_sys_0_0 || ORIG_REF_NAME==design_with_dvb_s2_rom_sys_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_sys_200m_rstgen_0/design_with_dvb_s2_sys_200m_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_sys_200m_rstgen_0 || ORIG_REF_NAME==design_with_dvb_s2_sys_200m_rstgen_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_sys_concat_intc_0/design_with_dvb_s2_sys_concat_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_sys_concat_intc_0 || ORIG_REF_NAME==design_with_dvb_s2_sys_concat_intc_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_sys_ps7_0/design_with_dvb_s2_sys_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_sys_ps7_0 || ORIG_REF_NAME==design_with_dvb_s2_sys_ps7_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_sys_rstgen_0/design_with_dvb_s2_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_sys_rstgen_0 || ORIG_REF_NAME==design_with_dvb_s2_sys_rstgen_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_adc_fifo_0/design_with_dvb_s2_util_ad9361_adc_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_adc_fifo_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_adc_pack_0/design_with_dvb_s2_util_ad9361_adc_pack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_adc_pack_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_adc_pack_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_dac_upack_0/design_with_dvb_s2_util_ad9361_dac_upack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_dac_upack_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_dac_upack_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_divclk_0/design_with_dvb_s2_util_ad9361_divclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_divclk_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_divclk_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_divclk_reset_0/design_with_dvb_s2_util_ad9361_divclk_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_divclk_reset_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_divclk_sel_0/design_with_dvb_s2_util_ad9361_divclk_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_divclk_sel_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_divclk_sel_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_ad9361_divclk_sel_concat_0/design_with_dvb_s2_util_ad9361_divclk_sel_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_ad9361_divclk_sel_concat_0 || ORIG_REF_NAME==design_with_dvb_s2_util_ad9361_divclk_sel_concat_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_dma_0_0 || ORIG_REF_NAME==design_with_dvb_s2_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_xlconcat_0_0/design_with_dvb_s2_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_xlconcat_0_0 || ORIG_REF_NAME==design_with_dvb_s2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_reduced_logic_0_0/design_with_dvb_s2_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_reduced_logic_0_0 || ORIG_REF_NAME==design_with_dvb_s2_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_fifo_mm_s_0_3/design_with_dvb_s2_axi_fifo_mm_s_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axi_fifo_mm_s_0_3 || ORIG_REF_NAME==design_with_dvb_s2_axi_fifo_mm_s_0_3} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_util_vector_logic_0_0/design_with_dvb_s2_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_util_vector_logic_0_0 || ORIG_REF_NAME==design_with_dvb_s2_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_axis_clock_converter_0_2/design_with_dvb_s2_axis_clock_converter_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_axis_clock_converter_0_2 || ORIG_REF_NAME==design_with_dvb_s2_axis_clock_converter_0_2} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_dvbs2_encoder_wrapper_1_0/design_with_dvb_s2_dvbs2_encoder_wrapper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_dvbs2_encoder_wrapper_1_0 || ORIG_REF_NAME==design_with_dvb_s2_dvbs2_encoder_wrapper_1_0} -quiet] -quiet

# IP: bd/design_with_dvb_s2/ip/design_with_dvb_s2_auto_pc_0/design_with_dvb_s2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_with_dvb_s2_auto_pc_0 || ORIG_REF_NAME==design_with_dvb_s2_auto_pc_0} -quiet] -quiet

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/design_with_dvb_s2_ooc.xdc
