# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.srcs/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0.xci
# IP: The module: 'design_with_dvb_s2_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.srcs/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0.xci
# IP: The module: 'design_with_dvb_s2_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/krisemi_satcom/adi/hdl/projects/fmcomms2/zc702/fmcomms2_zc702.gen/sources_1/bd/design_with_dvb_s2/ip/design_with_dvb_s2_axi_dma_0_0/design_with_dvb_s2_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_with_dvb_s2_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
